global:
  hostAliases:
    - ip: 185.199.109.153
      hostnames:
        - zotregistry.dev
  image:
    tag: "v2.11.1"
repoServer:
  env:
    - name: ARGOCD_EXEC_TIMEOUT
      value: 10m
#server:
# certificate:
#    enabled: false

configs:
  params:
    server.insecure: true
    controller.self.heal.timeout.seconds: 180
server:
  service:
    type: 'LoadBalancer'
    servicePortHttps: 4443
