---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app: controller
  name: controller
  namespace: knative-serving
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-serving
  selector:
    matchLabels:
      app: controller
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app: autoscaler
  name: autoscaler
  namespace: knative-serving
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-serving
  selector:
    matchLabels:
      app: autoscaler
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app: activator
  name: activator
  namespace: knative-serving
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-serving
  selector:
    matchLabels:
      app: activator
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app: webhook
  name: webhook
  namespace: knative-serving
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-serving
  selector:
    matchLabels:
      app: webhook
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app: broker-filter
  name: broker-filter
  namespace: knative-eventing
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-eventing
  selector:
    matchLabels:
      eventing.knative.dev/brokerRole: filter
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app: broker-ingress
  name: broker-ingress
  namespace: knative-eventing
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-eventing
  selector:
    matchLabels:
      eventing.knative.dev/brokerRole: ingress
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: eventing-controller
  labels:
    app: eventing-controller
  namespace: knative-eventing
spec:
  selector:
    matchLabels:
      app: eventing-controller
  namespaceSelector:
    matchNames:
    - knative-eventing
  podMetricsEndpoints:
  - honorLabels: true
    path: /metrics
    port: metrics
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: imc-controller
  namespace: knative-eventing
spec:
  selector:
    matchLabels:
      messaging.knative.dev/role: controller
  namespaceSelector:
    matchNames:
    - knative-eventing
  podMetricsEndpoints:
  - honorLabels: true
    path: /metrics
    port: metrics
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: ping-source
  namespace: knative-eventing
spec:
  selector:
    matchLabels:
      eventing.knative.dev/source: ping-source-controller
  namespaceSelector:
    matchNames:
    - knative-eventing
  podMetricsEndpoints:
  - honorLabels: true
    path: /metrics
    port: metrics
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: apiserver-source
  namespace: knative-eventing
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      eventing.knative.dev/source: apiserver-source-controller
  podMetricsEndpoints:
  - honorLabels: true
    path: /metrics
    port: metrics
