name: ci

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

env:
  TF_VAR_ssh_private_key: ${{ secrets.CI_SSH_KEY }}
  TF_VAR_linode_token: ${{ secrets.CI_LINODE_TOKEN }}
  TF_VAR_root_password: ${{ secrets.CI_ROOT_PASSWORD }}
  TF_DIR: "./tests/e2e"

jobs:
  ci:
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: terraform init
      working-directory: "${{ env.TF_DIR }}"
      run: terraform init

    - name: terraform plan
      working-directory: "${{ env.TF_DIR }}"
      run: terraform plan

    - name: terraform apply
      working-directory: "${{ env.TF_DIR }}"
      run: terraform apply -auto-approve
      continue-on-error: true

    - name: terraform destroy
      working-directory: "${{ env.TF_DIR }}"
      run: terraform destroy -auto-approve
