name: Renovate
on:
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Run Hello World in KCL Container
        run: |
          docker run --rm -v "$(pwd)":/workspace -w /workspace kcllang/kcl:v0.9.7 kcl run -o main.yaml
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.12
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.GITHUB_TOKEN }}
